name: awesome pr check
on:
  pull_request:
    branches: [main]
jobs:
  Awesome-PR-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Linter
        run: npx awesome-lint

      - name: Link Checker
        run: |
          gem install awesome_bot
          awesome_bot README.md --request-delay 1 --allow-dupe

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ab-results
          path: ab-results-README.md-filtered.json